[package]
name = "sled"
version = "0.34.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "a modern embedded database"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
categories = ["database-implementations", "concurrency", "data-structures", "algorithms", "caching"]
documentation = "https://docs.rs/sled/"
readme = "README.md"
edition = "2018"
exclude = ["benchmarks", "examples", "bindings", "scripts", "experiments"]

[package.metadata.docs.rs]
features = ["docs"]

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
debug = true
opt-level = 3

[features]
default = ["no_metrics"]
testing = ["event_log", "lock_free_delays", "compression", "failpoints", "backtrace"]
compression = ["zstd"]
lock_free_delays = []
failpoints = []
event_log = []
no_metrics = []
no_logs = ["log/max_level_off"]
no_inline = []
measure_allocs = []
pretty_backtrace = ["color-backtrace"]
io_uring = ["rio"]
docs = []
miri_optimizations = []
mutex = []

[dependencies]
crossbeam-epoch = "0.8.2"
crossbeam-utils = "0.7.2"
fxhash = "0.2.1"
libc = "0.2.72"
zstd = { version = "0.5.3", optional = true }
crc32fast = "1.2.0"
log = "0.4.8"
parking_lot = "0.11.0"
color-backtrace = { version = "0.4.2", optional = true }
rio = { version = "0.9.3", optional = true }
backtrace = { version = "0.3.50", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os="windows"))'.dependencies]
fs2 = "0.4.3"

[dev-dependencies]
rand = "0.7.3"
rand_chacha = "0.2.2"
rand_distr = "0.2.2"
quickcheck = "0.9.2"
log = "0.4.8"
env_logger = "0.7.1"
zerocopy = "0.3.0"
byteorder = "1.3.4"

[[test]]
name = "test_crash_recovery"
path = "tests/test_crash_recovery.rs"
harness = false
